// Titles complets pour 50 articles dont le <title> Ghost etait coupe en plein
// milieu de phrase (ex. « Agilite et Innovation : reussir dans un | Keep Growing »).
// Constat du crawl du 24/09/2026. Ecrits a partir du H1, 60 caracteres maximum.
// Appliques par applyMetaOverrides (title + og:title + twitter:title).
export const BLOG_TITLES = {
  'comment-implementer-les-okr-dans-une-pme-guide-pratique-2026': 'Implémenter les OKR dans une PME : guide pratique 2026',
  'comment-estimer-le-roi-dune-initiative-business-en-quelques-etapes': "Estimer le ROI d'une initiative business, étape par étape",
  'campagnes-dacquisition-et-growth-hacking-methodes-eprouvees': 'Campagnes d’acquisition et growth hacking B2B : méthodes',
  'business-partner-vs-consultant-commercial-difference': 'Business partner ou consultant commercial : la différence',
  'reset-commercial-q2-comment-redresser-ton-trimestre-avant-lt': 'Reset commercial : redresser ton trimestre avant l’été',
  'recommandations-clients-conversions': 'Recommandations clients : convertir grâce aux ambassadeurs',
  'pensee-rapide-et-pensee-lente-la-cle-du-leadership-efficace': 'Pensée rapide et pensée lente : la clé du leadership',
  'prospection-les-cles-dune-approche-gagnante': 'Prospection B2B : les clés d’une approche gagnante',
  'demos-qui-closent-lart-de-convaincre-et-conclure': 'Démos qui closent : convaincre et conclure en B2B',
  'entretiens-individuels-annuels-les-astuces-pour-booster': 'Entretiens annuels : booster la performance commerciale',
  'booster-vos-ventes-b2b-le-pouvoir-des-bonnes-strategies': 'Booster ses ventes B2B grâce au contenu : les stratégies',
  'curiosite-en-vente-posez-les-bonnes-questions': 'Curiosité en vente : poser les bonnes questions au client',
  'gestion-du-temps-optimisez-la-productivite-de-votre-equipe': 'Gestion du temps : la productivité de l’équipe commerciale',
  'agilite-et-innovation-reussir-dans-un-monde-en-constante': 'Agilité et innovation : réussir dans un monde qui change',
  'maitrisez-lart-des-reunions-clients-astuces-et-strategies': 'Réunions clients : astuces et stratégies pour convaincre',
  'cultiver-lexcellence-commerciale-prevenir-le-burn-out': 'Burn-out, bore-out, brown-out : protéger ses commerciaux',
  'lintelligence-emotionnelle-vendez-plus-en-comprenant-mieux': 'Intelligence émotionnelle : vendre plus en comprenant mieux',
  'le-principe-de-peter-excellent-vendeur-mais-pietre-directeur': 'Principe de Peter : bon vendeur, piètre directeur des ventes',
  'lego-la-plus-grosse-resistance-au-changement': 'L’ego, la plus grosse résistance au changement',
  'creation-de-valeur-a-travers-les-relations-clients': 'Créer de la valeur par la relation client en B2B',
  'pme-eti-la-transformation-digitale-de-votre-force': 'PME et ETI : digitaliser votre force commerciale',
  'lart-de-lentretien-annuel-au-sein-dune-equipe': 'Entretien annuel en équipe commerciale : le mener bien',
  'methode-ecart-gerez-les-objections-clients-avec-elegance': 'Méthode ECART : traiter les objections clients avec élégance',
  'bbedc-deverrouillez-votre-succes-commercial-avec-une-methode': 'Méthode BBEDC : une approche holistique de la vente',
  'champ-la-nouvelle-ere-de-qualification-client': 'Méthode CHAMP : la nouvelle qualification client en B2B',
  'gestion-de-grands-comptes-quelle-methode-choisir-une-analyse': 'Gestion de grands comptes : quelle méthode choisir ?',
  'integration-de-la-rse-dans-le-bmc-un-engagement-pour-avenir': 'Intégrer la RSE dans le Business Model Canvas',
  'intelligence-collective-et-co-developpement-une-approche': 'Co-développement en équipe commerciale : la méthode',
  'structure-de-decision-lart-prendre-les-bonnes-decisions': 'Structure de décision : bien décider en collectif',
  'lart-de-bien-sentourer-en-tant-que-dirigeant-startup-cle': 'Dirigeant de startup : l’art de bien s’entourer',
  'les-resistances-au-pivot-naviguer-le-changement-avec-sagesse': 'Résistances au pivot : conduire le changement avec sagesse',
  'pivoter-avec-precision-lart-de-la-reorientation-en-startup': 'Pivot de startup : réussir sa réorientation stratégique',
  'domaines-dinnovation-envisageables-pour-une-equipe': 'Innover en équipe commerciale : les domaines à explorer',
  'cultiver-linnovation-le-role-pivotal-du-leadership': 'Cultiver l’innovation : le rôle clé du leadership',
  'l-agenda-des-priorites-de-la-vision-a-lexecution': 'L’agenda des priorités : de la vision à l’exécution',
  'remise-en-question-et-evolution-professionnelle': 'Remise en question et évolution professionnelle en vente',
  'les-4-axes-dinterventions-dun-sales-business-coach': 'Les 4 axes d’intervention d’un sales business coach',
  'la-gestion-de-performance-a-lumiere-du-coaching': 'Gérer la performance commerciale par le coaching',
  'la-structuration-de-lequipe-commerciale-le-deuxieme-moment': 'Structurer l’équipe commerciale : le 2e moment clé',
  'seminaire-de-fin-dannee-loccasion-reflechir-et-dinnover': 'Séminaire de fin d’année : réfléchir et innover en équipe',
  'plan-daction-s2-de-la-strategie-a-piste-course': 'Plan d’action S2 : de la stratégie à l’exécution',
  'analyse-du-moteur-des-outils-et-processus-la-mecanique': 'Outils et processus commerciaux : réussir son S2',
  'les-sales-business-coach-votre-accelerateur-de-reussite': 'Sales business coach : l’accélérateur de votre réussite',
  'comment-equilibrer-les-objectifs-de-vente-sans-decourager': 'Objectifs de vente : les fixer sans décourager l’équipe',
  'le-danger-des-objectifs-trop-eleves-creer-une-culture': 'Objectifs trop élevés : le danger pour l’équipe commerciale',
  'maitriser-lart-du-pitch-trois-scenarios-pratiques': 'L’art du pitch commercial : 3 scénarios pratiques',
  'la-voie-traditionnelle-les-differents-modeles-de': 'Rémunération des commerciaux : les modèles classiques',
  'la-remuneration-des-commerciaux-un-levier-de-parmi-dautres': 'Rémunération des commerciaux : un levier parmi d’autres',
  'le-leadership-de-lequipe-commerciale-facteur-humain-au': 'Leadership commercial : le facteur humain au cœur',
  'la-neuroscience-et-psychologie-de-negociation': 'Neurosciences et psychologie de la négociation B2B',
};
